name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #- name: Generate Artifacts
      #  run: |
      #    npm install register-scheme
      #    npm install
      #    npm audit fix
      #    npm run dist:linux
      #    npm run dist:mac
      #    npm run dist:win
          
      - name: Pack Artifacts
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: AxolotlClient-Automated build
          #path: ./dist/AxolotlClient-${version}*#.AppImage, ./dist/*.exe, ./dist/*.dmg
          path: ./dist/*
