name: Dev-pre-release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Automatic Releases

        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: ${{secrets.github_token}}
          # Git tag (for automatic releases)
          automatic_release_tag: latest
          # Should this release be marked as a pre-release?
          prerelease: true
          # Release title (for automatic releases)
          title: Dev-pre-release (Possibly unstable)
          # Assets to upload to the release
          files: |
            dist/AxolotlClient-*
            dist/latest-*
